version: '3'
services:
  db:
    image: mysql:8.0.17
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - my-shared-network
  #
  transaction-logged:
    container_name: transaction-logged
    build:
      context: .
      dockerfile: Dockerfile
    image: realpac/transaction-logged
    ports:
      - 7080:7080
    environment:
      - DB_URI= jdbc:mysql://db:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db
    networks:
      - my-shared-network
    restart: always

networks:
  my-shared-network:
    driver: "bridge"