apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-dep
  labels:
    app: transaction-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-demo
  template:
    metadata:
      labels:
        app: transaction-demo
    spec:
      containers:
      - name: transaction-k8s
        image: realpac/transaction-demo
        ports:
        - containerPort: 9000
